---
label: Services
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: layout
  label: layout
- type: file
  name: hero-image
  label: hero-image
- type: text
  name: details
  label: details
- type: text
  name: image-1
  label: image-1
- type: text
  name: image-2
  label: image-2
- type: text
  name: image-3
  label: image-3
- type: text
  name: image-4
  label: image-4
- type: text
  name: image-5
  label: image-5
- type: text
  name: image-6
  label: image-6
- type: text
  name: image-7
  label: image-7
- type: text
  name: image-8
  label: image-8
- type: text
  name: next-url
  label: next-url
- type: text
  name: previous-url
  label: previous-url
- type: datetime
  name: date
  label: date
- type: list
  name: gallery
  label: gallery
- type: text
  name: image-count
  label: image-count
- type: text
  name: column-1
  label: column-1
- type: text
  name: column-2
  label: column-2
